const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('whiteboardAPI', {
  getDataPath: () => ipcRenderer.invoke('get-data-path'),
  ensureDataDir: () => ipcRenderer.invoke('ensure-data-dir'),
  addAsset: (buffer, filename) => ipcRenderer.invoke('add-asset', { buffer, filename }),
  getAsset: (assetId) => ipcRenderer.invoke('get-asset', assetId),
  getAssetThumbnail: (assetId) => ipcRenderer.invoke('get-asset-thumbnail', assetId),
  saveFile: (buffer, filename) => ipcRenderer.invoke('save-file', { buffer, filename }),
  readState: () => ipcRenderer.invoke('read-state'),
  writeState: (state) => ipcRenderer.invoke('write-state', state),
  saveItemState: (item) => ipcRenderer.invoke('save-item-state', item),
  deleteItemState: (assetId) => ipcRenderer.invoke('delete-item-state', assetId),
  openFile: (assetId) => ipcRenderer.invoke('open-file', assetId),
  getFileIcon: (filename) => ipcRenderer.invoke('get-file-icon', filename),
  windowMinimize: () => ipcRenderer.invoke('window-minimize'),
  windowMaximize: () => ipcRenderer.invoke('window-maximize'),
  windowUnmaximize: () => ipcRenderer.invoke('window-unmaximize'),
  windowClose: () => ipcRenderer.invoke('window-close'),
  windowIsMaximized: () => ipcRenderer.invoke('window-is-maximized'),
  readClipboardImage: () => ipcRenderer.invoke('read-clipboard-image'),
  readClipboardFiles: () => ipcRenderer.invoke('read-clipboard-files'),
  readFileAsBase64: (filePath) => ipcRenderer.invoke('read-file-as-base64', filePath),
  selectLibraryFolder: () => ipcRenderer.invoke('select-library-folder'),
  createLibrary: () => ipcRenderer.invoke('create-library'),
  addLibrary: (libPath) => ipcRenderer.invoke('add-library', libPath),
  getLibraries: () => ipcRenderer.invoke('get-libraries'),
  setActiveLibrary: (libId) => ipcRenderer.invoke('set-active-library', libId),
  removeLibrary: (libId) => ipcRenderer.invoke('remove-library', libId),
  showCardContextMenu: (data) => ipcRenderer.invoke('show-card-context-menu', data),
  addTimer: (itemId, hours, minutes) => ipcRenderer.invoke('add-timer', { itemId, hours, minutes }),
  setTimer: (itemId, hours, minutes) => ipcRenderer.invoke('set-timer', { itemId, hours, minutes }),
  onLibraryChanged: (callback) => ipcRenderer.on('library-changed', (e, libId) => callback(libId)),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  windowShow: () => ipcRenderer.invoke('window-show'),
  windowHide: () => ipcRenderer.invoke('window-hide'),
  setCardThumbnail: (assetId, buffer) => ipcRenderer.invoke('set-card-thumbnail', { assetId, buffer }),
  onTimerAction: (callback) => ipcRenderer.on('timer-action', (e, data) => callback(data)),
  onCreateGroup: (callback) => ipcRenderer.on('create-group', (e, data) => callback(data)),
  onRemoveFromGroup: (callback) => ipcRenderer.on('remove-from-group', (e, data) => callback(data)),
  saveTagMeta: (meta) => ipcRenderer.invoke('save-tag-meta', meta),
  loadTagMeta: () => ipcRenderer.invoke('load-tag-meta')
});
